[platformio]
default_envs = gateway

[env]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200

[env:gateway]
build_src_filter =
  +<gateway.cpp>
lib_deps =
  ArduinoJson

[tc_node_common]
build_src_filter =
  +<tc_node.cpp>
lib_deps =
  Adafruit MAX31855 library

[env:temp1]
build_src_filter = ${tc_node_common.build_src_filter}
lib_deps = ${tc_node_common.lib_deps}
build_flags = -D NODE_ID=1

[env:temp2]
build_src_filter = ${tc_node_common.build_src_filter}
lib_deps = ${tc_node_common.lib_deps}
build_flags = -D NODE_ID=2

[env:temp3]
build_src_filter = ${tc_node_common.build_src_filter}
lib_deps = ${tc_node_common.lib_deps}
build_flags = -D NODE_ID=3

[env:temp4]
build_src_filter = ${tc_node_common.build_src_filter}
lib_deps = ${tc_node_common.lib_deps}
build_flags = -D NODE_ID=4

[env:temp5]
build_src_filter = ${tc_node_common.build_src_filter}
lib_deps = ${tc_node_common.lib_deps}
build_flags = -D NODE_ID=5

[env:temp6]
build_src_filter = ${tc_node_common.build_src_filter}
lib_deps = ${tc_node_common.lib_deps}
build_flags = -D NODE_ID=6

[env:temp7]
build_src_filter = ${tc_node_common.build_src_filter}
lib_deps = ${tc_node_common.lib_deps}
build_flags = -D NODE_ID=7

[env:temp8]
build_src_filter = ${tc_node_common.build_src_filter}
lib_deps = ${tc_node_common.lib_deps}
build_flags = -D NODE_ID=8
